import React from 'react';

/**
 * The Omnia mark: six concentric segmented rings, blue and navy alternating.
 * Generated by var/brand/rings.mjs (a port of the console's `_RingsPainter`) —
 * regenerate there rather than editing the paths by hand.
 */
export const OmniaRings = ({
  size = 60,
  className,
}: {
  size?: number;
  className?: string;
}) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="0 0 60 60"
    fill="none"
    strokeWidth="4.5"
    strokeLinecap="round"
    className={className}
    aria-label="Omnia"
  >
    <path d="M30 1.13 A28.88 28.88 0 0 1 58.87 30.68" stroke="#1E56E8"/>
    <path d="M55.01 44.44 A28.88 28.88 0 0 1 14.98 54.66" stroke="#1E56E8"/>
    <path d="M4.99 44.44 A28.88 28.88 0 0 1 16.16 4.66" stroke="#1E56E8"/>
    <path d="M42.68 9.33 A24.25 24.25 0 0 1 51.8 40.63" stroke="#0A1F5C"/>
    <path d="M41.57 51.31 A24.25 24.25 0 0 1 9.9 43.56" stroke="#0A1F5C"/>
    <path d="M5.76 29.36 A24.25 24.25 0 0 1 28.3 5.81" stroke="#0A1F5C"/>
    <path d="M47.49 21.1 A19.63 19.63 0 0 1 42.45 45.17" stroke="#1E56E8"/>
    <path d="M28.96 49.6 A19.63 19.63 0 0 1 10.64 33.2" stroke="#1E56E8"/>
    <path d="M13.55 19.3 A19.63 19.63 0 0 1 36.91 11.63" stroke="#1E56E8"/>
    <path d="M44.95 31.19 A15 15 0 0 1 33.82 44.51" stroke="#0A1F5C"/>
    <path d="M21.5 42.36 A15 15 0 0 1 15.53 26.05" stroke="#0A1F5C"/>
    <path d="M23.55 16.46 A15 15 0 0 1 40.66 19.44" stroke="#0A1F5C"/>
    <path d="M38.39 36.11 A10.38 10.38 0 0 1 28.22 40.22" stroke="#1E56E8"/>
    <path d="M20.52 34.21 A10.38 10.38 0 0 1 22.04 23.34" stroke="#1E56E8"/>
    <path d="M31.09 19.68 A10.38 10.38 0 0 1 39.74 26.43" stroke="#1E56E8"/>
    <path d="M32.19 35.31 A5.75 5.75 0 0 1 26.74 34.74" stroke="#0A1F5C"/>
    <path d="M24.3 29.24 A5.75 5.75 0 0 1 27.53 24.81" stroke="#0A1F5C"/>
    <path d="M33.51 25.44 A5.75 5.75 0 0 1 35.73 30.45" stroke="#0A1F5C"/>
  </svg>
);
